SERVER_HOST = 'xiaohuihui.test.com'  # 192.168.179.133
SERVER_PORT = 22222
SERVER_DATA_PORT = 33333
CERT_PATH = 'common/server.crt'
KEY_PATH = 'server.key'
SERVER_URI = (SERVER_HOST, SERVER_PORT)
FILE_DIR = "./USER_FILES/"
